# Understanding Embedding Layers in PyTorch

This notebook explains the embedding process in PyTorch using an example with a large vocabulary size and embedding dimension.

## What is an Embedding Layer?

An embedding layer maps discrete input tokens (like words) into continuous vectors. It is used to represent words in a dense vector space where each word has its own unique vector representation.

### Why Use Embeddings?
- **Dimensionality Reduction:** Instead of one-hot encoding with a large dimension, embeddings provide a lower-dimensional representation.
- **Semantic Meaning:** Vectors can capture semantic relationships between words.

## Step-by-Step Explanation

### Step 1: Define the Vocabulary
For simplicity, we use a small subset of words to illustrate the process. In practice, the vocabulary can be much larger.

In [34]:
import torch
import torch.nn as nn

# Define a small vocabulary for illustration
vocab = {'<pad>': 0, '<unk>': 1, 'the': 2, 'to': 3, 'and': 4, 'of': 5, 'a': 6, 'in': 7, 'that': 8, 'is': 9, 'cat': 10, 'hat': 11}
vocab_size = len(vocab)

print(vocab_size)


12


## Step 2: Initialize the Embedding Layer
The embedding layer is initialized with a random matrix of size `(vocab_size, embedding_dim)`.

In [24]:
# Define the embedding dimension
embedding_dim = 512

# Initialize the embedding layer
embedding_layer = nn.Embedding(vocab_size, embedding_dim)

## Step 3: Embedding Matrix Initialization
The embedding matrix \( E \) has dimensions `(vocab_size, embedding_dim)`. Each row represents a word vector in the embedding space.

### Math Behind Embedding Initialization
For each word in the vocabulary, a unique vector of size `embedding_dim` is initialized. This matrix is updated during training to capture the relationships between words.

Let's initialize and inspect the embedding matrix.

In [25]:
# Inspect the size of the embedding matrix
embedding_matrix = embedding_layer.weight.data
embedding_matrix.size()

torch.Size([12, 512])

## Step 4: Input Sequence to Embeddings
Given an input sequence of token indices, the embedding layer retrieves the corresponding vectors from the embedding matrix.

In [37]:
# Example input sequence: "the cat in the hat"
input_indices = torch.tensor([2, 10, 7, 2, 11], dtype=torch.long)  # Example indices based on the vocab

# Get the embeddings for the input sequence
embeddings = embedding_layer(input_indices)

print(f"Input Sequence: {input_indices}")

Input Sequence: tensor([ 2, 10,  7,  2, 11])


## Step 5: Inspect the Embeddings
Each token index in the input sequence is mapped to its corresponding 512-dimensional vector.

In [36]:
embeddings

tensor([[ 0.1167, -2.6202,  0.8959,  0.2841,  0.2588, -0.6021, -0.0957,  0.2856,
          0.1735,  1.0869],
        [-0.2041,  0.5962, -2.1217,  0.8078,  0.2647, -1.1594, -1.3126, -0.4208,
         -1.2536, -1.6452],
        [ 0.0293,  0.0540,  0.0781, -0.1809, -0.9328, -0.9710, -0.1827, -0.4984,
          1.2441,  1.1407],
        [ 0.1167, -2.6202,  0.8959,  0.2841,  0.2588, -0.6021, -0.0957,  0.2856,
          0.1735,  1.0869],
        [-1.0875, -0.5282, -0.4345,  0.4412,  0.6763,  0.4563,  0.0057, -1.3187,
         -0.0275,  1.6703]], grad_fn=<EmbeddingBackward0>)

## Explanation of the Embeddings
- Each row in the output corresponds to a token in the input sequence.
- The values in each row are the learned weights representing the token in the 512-dimensional space.
- These embeddings capture the semantic meaning and relationships between words.

For example, words that are similar or often appear in similar contexts will have similar vector representations.

## Recap
1. **Vocabulary Size:** The number of unique tokens in the vocabulary (e.g., 10,000).
2. **Embedding Dimension:** The size of the vector representing each token (e.g., 512).
3. **Embedding Matrix:** A matrix of size `(vocab_size, embedding_dim)` initialized randomly.
4. **Token Indices:** Each word in the input sequence is converted to its corresponding index.
5. **Embedding Lookup:** The embedding layer retrieves the vectors for the input token indices, resulting in a sequence of vectors.

This process allows the model to learn and represent words in a continuous vector space, capturing their semantic relationships and improving the model's performance in tasks like text generation.

## Embeddings Passed to Positional Encoder

In a Transformer architecture, after converting tokens to embeddings, the embeddings are passed through the positional encoder. This step adds positional information to the embeddings, enabling the model to understand the order of the tokens.

## More in-depth look at Embeddings:

In [28]:
import torch
import torch.nn as nn

# Define the input text
text = """
This script implements a decoder-only Transformer model for text generation, similar to the architecture used in GPT (Generative Pre-trained Transformer). The model is trained on a text dataset, specifically the book "Pride and Prejudice," to learn to generate text in the style of the book.
The script trains the model on the text of "Pride and Prejudice" to generate text in a similar style. After training, the model can be used to generate text by predicting the next token in a sequence based on the previous tokens.
"""

# Tokenize the text and create the vocabulary
def create_vocab(text):
    words = text.split()
    print(f"Words: {words}")
    unique_words = set(words) # removes duplicates
    print(f"Unique Words: {words}")
    vocab = {word: i + 4 for i, word in enumerate(unique_words)} # create dict - map each word to a index
    print(f"Vocab: {vocab}")

    # Add special tokens to the vocabulary with fixed indices
    vocab['<pad>'] = 0
    vocab['<unk>'] = 1
    vocab['<sos>'] = 2
    vocab['<eos>'] = 3
    return vocab

vocab = create_vocab(text)
print("Vocabulary size:", len(vocab))
print("Sample vocabulary:", {k: vocab[k] for k in list(vocab)[:10]})

Words: ['This', 'script', 'implements', 'a', 'decoder-only', 'Transformer', 'model', 'for', 'text', 'generation,', 'similar', 'to', 'the', 'architecture', 'used', 'in', 'GPT', '(Generative', 'Pre-trained', 'Transformer).', 'The', 'model', 'is', 'trained', 'on', 'a', 'text', 'dataset,', 'specifically', 'the', 'book', '"Pride', 'and', 'Prejudice,"', 'to', 'learn', 'to', 'generate', 'text', 'in', 'the', 'style', 'of', 'the', 'book.', 'The', 'script', 'trains', 'the', 'model', 'on', 'the', 'text', 'of', '"Pride', 'and', 'Prejudice"', 'to', 'generate', 'text', 'in', 'a', 'similar', 'style.', 'After', 'training,', 'the', 'model', 'can', 'be', 'used', 'to', 'generate', 'text', 'by', 'predicting', 'the', 'next', 'token', 'in', 'a', 'sequence', 'based', 'on', 'the', 'previous', 'tokens.']
Unique Words: ['This', 'script', 'implements', 'a', 'decoder-only', 'Transformer', 'model', 'for', 'text', 'generation,', 'similar', 'to', 'the', 'architecture', 'used', 'in', 'GPT', '(Generative', 'Pre-traine

In [29]:
# Define the embedding layer
vocab_size = len(vocab)  # Example vocabulary size
print(f"Vocab Size: {vocab_size}")

embedding_dim = 10  # Embedding dimension
embedding_layer = nn.Embedding(vocab_size, embedding_dim)
print(f"Embedding Matrix Shape: {embedding_layer}")

# Extract the embedding matrix
embedding_matrix = embedding_layer.weight.data

print("Embedding Matrix:")
print(embedding_matrix)


Vocab Size: 54
Embedding Matrix Shape: Embedding(54, 10)
Embedding Matrix:
tensor([[ 1.7817e+00, -2.4578e-01, -1.9288e+00, -2.3736e+00, -1.7667e+00,
         -1.3655e-01,  2.1512e-01,  4.9012e-01, -2.0669e-01, -1.2839e+00],
        [-9.0111e-01,  2.2189e-01, -7.3052e-01, -9.3051e-01, -1.1411e+00,
          1.8688e-01, -6.2162e-02,  5.5358e-01, -5.3468e-01, -4.7860e+00],
        [ 1.1667e-01, -2.6202e+00,  8.9586e-01,  2.8406e-01,  2.5875e-01,
         -6.0208e-01, -9.5742e-02,  2.8559e-01,  1.7346e-01,  1.0869e+00],
        [-5.3958e-01,  1.1930e+00, -1.4879e+00, -1.1899e-01, -2.4420e-02,
          7.0628e-01, -1.9891e+00,  1.5592e-01, -1.0137e-01,  1.3473e+00],
        [-5.0485e-01, -3.4236e-01,  2.2111e-01,  2.7366e-03,  1.0548e+00,
          4.9219e-02,  3.8879e-01, -1.9308e-01, -1.6287e+00, -5.0560e-01],
        [-5.0615e-01, -7.6137e-01, -7.9958e-01,  2.1156e-01, -5.4082e-01,
          1.0898e+00, -7.4317e-01,  1.2753e+00,  8.7972e-01, -2.2844e+00],
        [-4.5271e-01, -4.8495e-

An embedding matrix of shape (54, 10) is created. Each row in this matrix corresponds to a word vector of size 10.  We can also print out the full Embedding Matrix as shown above.

### Extract the First Sentence and Convert to Indices

In [30]:
first_sentence = "This script implements a decoder-only Transformer model for text generation"
first_sentence_indices = [vocab.get(word, vocab['<unk>']) for word in first_sentence.split()]
print(f"Sentence indicies: {first_sentence_indices}")

# Turn it into a tensor for processing
input_indices = torch.tensor(first_sentence_indices, dtype=torch.long)
print(f"Input indices: {input_indices}")


Sentence indicies: [30, 33, 16, 19, 47, 29, 35, 51, 31, 1]
Input indices: tensor([30, 33, 16, 19, 47, 29, 35, 51, 31,  1])


### Get the embeddings for the input sequence

In [31]:
embeddings = embedding_layer(input_indices)

Retrieve the corresponding rows from the embedding matrix  E  for each index.

So, If first_sentence_indices = [21, 6, 15, 8, 53, 50, 34, 24, 1], the corresponding embeddings would be something like this:

In [32]:
embeddings_example = [
 [0.5, 0.6, ..., 0.8],  # Embedding for 'This' (index 21)
 [0.3, 0.4, ..., 0.7],  # Embedding for 'script' (index 6)
 [0.7, 0.1, ..., 0.9],  # Embedding for 'implements' (index 15)
 [0.4, 0.5, ..., 0.6],  # Embedding for 'decoder-only' (index 8)
 [0.2, 0.3, ..., 0.4],  # Embedding for 'Transformer' (index 53)
 [0.4, 0.5, ..., 0.6],  # Embedding for 'model' (index 50)
 [0.1, 0.2, ..., 0.3],  # Embedding for 'for' (index 34)
 [0.3, 0.4, ..., 0.7],  # Embedding for 'text' (index 24)
 [0.3, 0.4, ..., 0.7],  # Embedding for 'generation' (<unk>, index 1)
]

However, let's get the actualy Embeddings from the first_sentence_indices:

In [33]:
print("Embeddings shape: ", embeddings.shape)

print(f"\nfirst_sentence_indices Embeddings: \n\n{embeddings}")

Embeddings shape:  torch.Size([10, 10])

first_sentence_indices Embeddings: 

tensor([[ 1.9610e+00,  6.9433e-02, -7.7523e-01, -5.0131e-01,  1.5952e-01,
         -9.3172e-02, -2.8983e-01,  1.3627e+00,  1.4468e-01,  3.0185e-02],
        [-5.0942e-01, -2.0769e+00, -1.0320e+00, -1.1549e+00,  4.8648e-01,
         -2.5315e-01, -9.9709e-01, -2.7978e-01,  8.1825e-01, -4.4276e-01],
        [-8.0235e-01, -9.8867e-01,  1.0784e+00,  3.0479e+00, -8.3420e-01,
          9.6970e-01,  2.0081e-01,  8.3243e-01,  2.1970e+00,  1.0890e+00],
        [ 7.2014e-01,  1.7064e-02, -3.1708e-01, -1.5422e+00, -1.9077e+00,
          1.5713e+00,  2.1209e+00,  2.1159e+00,  1.4458e+00, -1.7229e+00],
        [-1.4564e+00, -7.5249e-01,  5.4608e-01,  6.9959e-01, -8.8782e-01,
         -2.1205e-04,  1.3236e-01,  1.6614e+00,  5.6530e-01,  1.6272e+00],
        [-6.9540e-01, -6.5679e-01, -1.7060e+00,  1.1546e+00,  2.1852e+00,
         -1.3217e+00, -3.5724e-01, -1.1262e+00, -4.1110e-01,  8.6602e-01],
        [-1.6193e+00, -1.838